require "core.options"
require "core.keymaps"
require "core.plugins"
require "core.colorscheme"

require "plugins.cmp"
require "plugins.lsp"
require "plugins.telescope"
require "plugins.treesitter"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.gitsigns"
require "plugins.nvim-tree"
require "plugins.bufferline"
